services:
  hawser:
    container_name: hawser
    restart: unless-stopped
    image: ghcr.io/finsys/hawser:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/alex/.ssl:/certs:ro
    ports:
      - "2376:2376"
    environment:
      TOKEN: ${HAWSER_TOKEN}
      TLS_CERT: /certs/dockhand.crt
      TLS_KEY: /certs/dockhand.key   
    labels:
      - dockhand.update=false

