services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    networks:
      proxy:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "82:80/tcp"
#      - "443:443/tcp"
#      - "443:443/udp"
#      - "3000:3000/tcp"
    volumes:
      - /home/alex/docker/adguardhome/work:/opt/adguardhome/work
      - /home/alex/docker/adguardhome/conf:/opt/adguardhome/conf
    security_opt: 
      - no-new-privileges
    labels: 
      - "traefik.enable=true" # Enable Traefik on this service
      - "traefik.http.routers.adguardhome.entrypoints=https" # Secure entrypoint for HTTPS
      - "traefik.http.routers.adguardhome.rule=Host(`adguardhome.homelab.ru`)"  # Host rule for secure routing
      - "traefik.http.routers.adguardhome.tls=true" # Enable TLS for secure connection
      - "traefik.http.routers.adguardhome.middlewares=security-headers@file"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=80"
networks:
  proxy:
    name: proxy 
    external: true
