services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - /home/alex/data/uptime-kuma/data:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "8084:3001"
