#!/bin/bash

obsidian_path=/home/$USER/data/Obsidian
kp_path=/home/$USER/data/Passwords
repo_path=/home/$USER/gitbackup/repo
gpg_keyname=data

rm -rfv "$repo_path"/**

tar --zstd -cf "$repo_path"/obsidian.zst "$obsidian_path" 
gpg --encrypt --recipient "$gpg_keyname" "$repo_path"/obsidian.zst 
rm "$repo_path"/obsidian.zst

tar --zstd -cf "$repo_path"/kp.zst "$kp_path" 
gpg --encrypt --recipient "$gpg_keyname" "$repo_path"/kp.zst 
rm "$repo_path"/kp.zst

cd "$repo_path"
git add .
git commit -m "$(date)"
git push -u origin main
