services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
#    ports:
#      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
#      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations, see alternative methods
    env_file:
      - /home/alex/docker/homepage/.env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.homelab.ru # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      PUID: 1000
      PGID: 1000
    restart: unless-stopped
    security_opt: 
      - no-new-privileges
    networks:
      proxy:
    labels: 
      - "traefik.enable=true" # Enable Traefik on this service
      - "traefik.http.routers.homepage.entrypoints=https" # Secure entrypoint for HTTPS
      - "traefik.http.routers.homepage.rule=Host(`homepage.homelab.ru`)"  # Host rule for secure routing
      - "traefik.http.routers.homepage.tls=true" # Enable TLS for secure connection
      - "traefik.http.routers.homepage.middlewares=security-headers@file,authelia@docker"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
networks:
  proxy:
    name: proxy 
    external: true
